version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_URL=http://localhost:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    command: npm run dev
    stdin_open: true
    tty: true
    restart: unless-stopped
